In [27]:
#https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[ 4.1735e-39,  5.5024e-11,  2.5353e+30],
        [ 6.5861e-44,  1.7379e-41,  4.5408e-39],
        [ 1.4086e-08,  9.0072e+15,  1.8522e+28],
        [ 1.8057e+28,  5.6449e-08,  2.5353e+30],
        [ 7.2868e-44,  1.9173e-41,  5.0000e-39]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[ 0.5071,  0.5163,  0.6469],
        [ 0.6259,  0.0830,  0.5264],
        [ 0.0577,  0.3860,  0.7111],
        [ 0.5543,  0.7880,  0.2902],
        [ 0.9385,  0.6245,  0.9487]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)
print (type(x))

tensor([ 5.5000,  3.0000])
<class 'torch.Tensor'>


In [7]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]], dtype=torch.float64)


In [8]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[-0.1818, -0.6929, -1.1054],
        [-0.7829, -0.0181, -0.6667],
        [ 1.0082,  0.4471,  0.5592],
        [-0.0762,  1.7889,  0.2351],
        [ 0.5965, -0.3880,  0.0589]])


In [9]:
print(x.size())

torch.Size([5, 3])


In [10]:
torch.Size([5, 3])

torch.Size([5, 3])

In [11]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.3524, -0.4272, -0.1217],
        [-0.7333,  0.5948, -0.3137],
        [ 1.2374,  1.1536,  1.0276],
        [ 0.8556,  1.9168,  0.8329],
        [ 0.9376, -0.0197,  0.4161]])


In [12]:
print(torch.add(x, y))

tensor([[ 0.3524, -0.4272, -0.1217],
        [-0.7333,  0.5948, -0.3137],
        [ 1.2374,  1.1536,  1.0276],
        [ 0.8556,  1.9168,  0.8329],
        [ 0.9376, -0.0197,  0.4161]])


In [13]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.3524, -0.4272, -0.1217],
        [-0.7333,  0.5948, -0.3137],
        [ 1.2374,  1.1536,  1.0276],
        [ 0.8556,  1.9168,  0.8329],
        [ 0.9376, -0.0197,  0.4161]])


In [14]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.3524, -0.4272, -0.1217],
        [-0.7333,  0.5948, -0.3137],
        [ 1.2374,  1.1536,  1.0276],
        [ 0.8556,  1.9168,  0.8329],
        [ 0.9376, -0.0197,  0.4161]])


In [15]:
print(x[:, 1])

tensor([-0.6929, -0.0181,  0.4471,  1.7889, -0.3880])


In [17]:
x = torch.randn(4, 4)
print (type(x))
y = x.view(16)
#torch.Tensor.view reshapes the tensor
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

<class 'torch.Tensor'>
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [18]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([ 0.4681])
0.4680952727794647


In [21]:
a = torch.ones(5)
print(a)
print (type(a), a.shape)

tensor([ 1.,  1.,  1.,  1.,  1.])
<class 'torch.Tensor'> torch.Size([5])


In [20]:
b = a.numpy()
print(b)
print (type(b), b.shape)

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'> (5,)


In [22]:
a.add_(1)
print(a)
print(b)

tensor([ 2.,  2.,  2.,  2.,  2.])
[1. 1. 1. 1. 1.]


In [25]:
import numpy as np
a = np.ones(5)
print ("type(a):", type(a))
b = torch.from_numpy(a)
print ("b=torch.from_numpy(a), type(b):", type(b))
np.add(a, 1, out=a)
print ("after adding to a, type(a):", type(a))
print(a)
print(b)

type(a): <class 'numpy.ndarray'>
b=torch.from_numpy(a), type(b): <class 'torch.Tensor'>
after adding to a, type(a): <class 'numpy.ndarray'>
[2. 2. 2. 2. 2.]
tensor([ 2.,  2.,  2.,  2.,  2.], dtype=torch.float64)


In [26]:
torch.cuda.is_available()

False